node {
  def app
  def nginx

  stage('Clone Repo') {
    checkout scm
  }

  stage('Build app') {
    app = docker.build('f3rnand3s/app', 'app/')
  }

  stage('Test app') {
    app.inside('-p 30001:3000'){
      dir('app') {
        sh 'npm install --cache /tmp/empty-cache'
        sh 'npm test'
      }
    }
  }

  // stage('Push app image') {
  //   docker.withRegistry('https://registry.hub.docker.com/f3rnand3s/app', 'docker-creds') {
  //     app.push("${env.BUILD_NUMBER}")
  //     app.push("latest")
  //   }
  //   echo "Pushing app Docker image to DockerHub"
  // }

  //*********************************************

  stage('Build nginx') {
    nginx = docker.build('f3rnand3s/nginx', 'nginx/')
  }

  stage('Test nginx') {
    nginx.inside {
      echo "Testing..."
      sh 'ls -la'
      dir('nginx') {
        sh 'nginx -v'
        sh 'pwd'
        sh 'ls -la'
        sh 'nginx -c /default.conf -t'
      }
    }
  }

  // stage('Push nginx image') {
  //   docker.withRegistry('https://registry.hub.docker.com/f3rnand3s/nginx', 'docker-creds') {
  //     app.push("${env.BUILD_NUMBER}")
  //     app.push("latest")
  //   }
  //   echo "Pushing nginx Docker image to DockerHub"
  // }

  stage('Clean up') {
    sh 'rm -rf *'
  }
}