node {
  def app
  def nginx

  stage('Clone Repo') {
    checkout scm
  }

  stage('Build app') {
    app = docker.build('f3rnand3s/app', 'app/')
  }

  stage('Test app') {
    app.inside {
      dir('app') {
        sh 'pwd'
        // sh 'npm install'
        // sh 'npm test'
      }
    }
  }

  // stage('Push app image') {
  //   docker.withRegistry('https://registry.hub.docker.com/f3rnand3s/app', 'docker-creds') {
  //     app.push("${env.BUILD_NUMBER}")
  //     app.push("latest")
  //   }
  //   echo "Pushing app Docker image to DockerHub"
  // }

  //*********************************************

  stage('Build nginx') {
    nginx = docker.build('f3rnand3s/nginx', 'nginx/')
  }

  stage('Test nginx') {
    nginx.inside {
      echo "Testing..."
      dir('nginx') {
        sh 'curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://localhost:3000'
      }
    }
  }

  // stage('Push nginx image') {
  //   docker.withRegistry('https://registry.hub.docker.com/f3rnand3s/nginx', 'docker-creds') {
  //     app.push("${env.BUILD_NUMBER}")
  //     app.push("latest")
  //   }
  //   echo "Pushing nginx Docker image to DockerHub"
  // }

  stage('Clean up') {
    sh 'rm -rf *'
  }
}