pipeline {
  environment {
    registry = "https://github.com/f3rnand3s/CICD"
    registryCredential = "docker-creds"
  }
  agent any
    stages {
        stage('SCM Checkout'){
          steps {
            git 'https://github.com/f3rnand3s/CICD'
          }
        }

        // stage('Docker Images Setup') {
        //   steps {
        //     sh 'docker build -t app:jenkins ./app'
        //     sh 'docker build -t nginx:jenkins ./nginx'
        //   }
        // }

        stage('Build APP') {
          steps {
            sh 'rm -rf *'
            sh 'git clone -b development --single-branch https://github.com/f3rnand3s/CICD'
            echo 'Welcome to the Build APP Stage!'
            sh 'pwd'
            sh 'ls -la '
            sh 'docker build -t app:jenkins CICD/app/.'
            sh 'docker rmi app:jenkins'
          }
        }

        stage('Build nginx image') {
          steps {
            echo 'Welcome to the Build nginx Stage!'
            sh 'pwd'
            sh 'ls -la '
            echo $BUILD_NUMBER
            sh 'docker build -t nginx:jenkins CICD/nginx/.'
            sh 'docker rmi nginx:jenkins'
          }
        }

        stage('Testing') {
          steps {
            echo 'Welcome to the Testing Stage!'
          }
        }

        // stage('Deploy Image!') {
        //   steps {
        //     echo 'Deploy Image Phase!'
        //     script {
        //       docker.withRegistry( '', registryCredential) {
        //         dockerImage.push()
        //       }
        //     }
        //   }
        // }

        stage('Cleanup') {
          steps {
            echo 'Welcome to the Cleanup Stage!'
            sh 'ls -la'
            sh 'rm -rf *'
            sh 'ls -la'
          }
        }
    }
}

