FROM nginx:latest

# RUN rm /etc/nginx/conf.d /*
# COPY proxy.conf /etc/nginx/conf.d/

#config 
COPY ./default.conf /etc/nginx/conf.d/default.conf
#                   /etc/nginx/conf.d/default.conf
#                   /etc/nginx/nginx.conf